repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: mixed-line-ending
      - id: check-added-large-files

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.8.0-2
    hooks:
      - id: shfmt
        args: ["-w", "-i", "2", "-ci"]

  - repo: local
    hooks:
      - id: prettier
        name: prettier (format)
        entry: npx prettier -w .
        language: system
        pass_filenames: false

      - id: eslint
        name: eslint (js lint)
        entry: npx eslint .
        language: system
        pass_filenames: false

      - id: stylelint
        name: stylelint (css lint)
        entry: npx stylelint "**/*.{css,scss}"
        language: system
        pass_filenames: false
